apiVersion: apps/v1
kind: Deployment
metadata: 
  name: event-bus-depl
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: event-bus
  template:
    metadata: 
      labels: 
        app: event-bus
    spec: 
      containers:
        - name: event-bus
          image: jonas/event-bus:0.0.1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi