apiVersion: apps/v1
kind: Deployment
metadata: 
  name: posts-depl
specs: 
  replicas: 1
  selector:
    matchLabels: 
      app: posts
  template:
    metadata: 
      labels: 
        app: posts
    spec: 
      containers:
        - name: posts
          image: jonas/posts:0.0.1
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi